/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaz;

import Clases.Funciones;
import Clases.Mostrador;
import Clases.Paso;
import java.awt.Color;
import java.awt.HeadlessException;

import java.util.List;
import java.util.ListIterator;
import javax.swing.JOptionPane;

/**
 *
 * @author Azahara
 */
public final class Simulacion extends javax.swing.JFrame {
  
    // ATRIBUTOS USADOS EN LA SIMULACIÓN
    private Paso paso = new Paso();
    private boolean botonPulsado = false;
    private boolean botonE1 = false;
    private boolean botonE2 = false;
    
    /**
     * Creates new form Simulación
     */
    public Simulacion() {
        initComponents();
        this.getContentPane().setBackground(Color.white);        
        this.setVisible(true);
        
        // Iniciamos la clase funciones que hace que la simulación comience
        Funciones f = new Funciones(paso, this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        textFieldE2 = new javax.swing.JTextPane();
        jScrollPane4 = new javax.swing.JScrollPane();
        textFieldE1 = new javax.swing.JTextPane();
        jScrollPane6 = new javax.swing.JScrollPane();
        textMost = new javax.swing.JTextArea();
        jScrollPane7 = new javax.swing.JScrollPane();
        textMesa = new javax.swing.JTextArea();
        jScrollPane5 = new javax.swing.JScrollPane();
        textFieldC2 = new javax.swing.JTextPane();
        jScrollPane8 = new javax.swing.JScrollPane();
        textFieldC3 = new javax.swing.JTextPane();
        jScrollPane9 = new javax.swing.JScrollPane();
        textFieldC1 = new javax.swing.JTextPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Contenido del mostrador:");

        jLabel2.setText("Empleado 1:");

        jLabel3.setText("Empleado 2:");

        jLabel4.setText("Cocinero 1:");

        jLabel5.setText("Cocinero 2:");

        jLabel6.setText("Contenido de la mesa de platos:");

        jLabel7.setText("Cocinero 3:");

        jButton1.setText("Pausar simulación");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Pausar Empleado 1");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Pausar Empleado 2");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jScrollPane3.setViewportView(textFieldE2);

        jScrollPane4.setViewportView(textFieldE1);

        textMost.setColumns(20);
        textMost.setRows(5);
        jScrollPane6.setViewportView(textMost);

        textMesa.setColumns(20);
        textMesa.setRows(5);
        jScrollPane7.setViewportView(textMesa);

        jScrollPane5.setViewportView(textFieldC2);

        jScrollPane8.setViewportView(textFieldC3);

        jScrollPane9.setViewportView(textFieldC1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel3)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 337, Short.MAX_VALUE)
                    .addComponent(jLabel2)
                    .addComponent(jScrollPane3)
                    .addComponent(jScrollPane4)
                    .addComponent(jScrollPane6)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 181, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 337, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(76, 76, 76))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(157, 157, 157)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane8)
                            .addComponent(jScrollPane7, javax.swing.GroupLayout.DEFAULT_SIZE, 339, Short.MAX_VALUE)
                            .addComponent(jScrollPane5)
                            .addComponent(jScrollPane9))
                        .addContainerGap(98, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(jLabel7))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(19, 19, 19)
                        .addComponent(jLabel3)
                        .addGap(20, 20, 20)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane8, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(38, 38, 38)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(48, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if(!botonPulsado) //Si no se ha pulsado
        {                
            botonPulsado=true;             //lo cambiamos a pulsado
            jButton1.setText("Reanudar simulación");  //y cambiamos el texto
            paso.cerrar();    //Cerramos el paso para que la simulación se detenga
        }
        else //Si ya se había pulsado
        {                          
            botonPulsado=false;            //lo cambiamos
            jButton1.setText("Pausar simulación");  //y cambiamos el texto
            paso.abrir();    //Abrimos el paso para que la simulación siga ejecutandose
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        if(!botonE1) //Si no se ha pulsado
        {                
            botonE1=true;             //lo cambiamos a pulsado
            jButton2.setText("Reanudar Empleado 1");  //y cambiamos el texto
            paso.cerrarE("Empleado1");    //Cerramos el paso para que el empleado 1 se detenga
        }
        else //Si ya se había pulsado
        {                          
            botonE1=false;            //lo cambiamos
            jButton2.setText("Pausar Empleado 1");  //y cambiamos el texto
            paso.abrirE("Empleado1");    //Abrimos el paso para que el empleado 1 siga trabajando
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        if(!botonE2) //Si no se ha pulsado
        {                
            botonE2=true;             //lo cambiamos a pulsado
            jButton3.setText("Reanudar Empleado 2");  //y cambiamos el texto
            paso.cerrarE("Empleado2");    //Cerramos el paso para que el empleado 2 se detenga
        }
        else //Si ya se había pulsado
        {                          
            botonE2=false;            //lo cambiamos
            jButton3.setText("Pausar Empleado 2");  //y cambiamos el texto
            paso.abrirE("Empleado2");    //Abrimos el paso para que el empleado 2 siga trabajando
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    public javax.swing.JTextPane textFieldC1;
    public javax.swing.JTextPane textFieldC2;
    public javax.swing.JTextPane textFieldC3;
    public javax.swing.JTextPane textFieldE1;
    public javax.swing.JTextPane textFieldE2;
    public javax.swing.JTextArea textMesa;
    public javax.swing.JTextArea textMost;
    // End of variables declaration//GEN-END:variables
}
